---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: odh-cluster-role
rules:
  - apiGroups: ["datasciencecluster.opendatahub.io"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["image.openshift.io"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["kubeflow.org"]
    resources: ["notebooks"]
    verbs: ["*"]
